services:
  best-practice.db:
    image: postgres:15-alpine
    container_name: best-practice.db
    environment:
      - TZ=Asia/Seoul
      - POSTGRES_USER=postgres
      - POSTGRES_DB=best-practice
      - POSTGRES_PASSWORD_FILE=/run/secrets/pg_password
    volumes:
      - ./volumes/pg_data:/var/lib/postgresql/data/
    ports:
      - "15432:5432"
    restart: on-failure
    secrets:
      - pg_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

secrets:
  pg_password:
    file: ./volumes/pg_password.txt

volumes:
  db_data:
